M48
; DRILL file {KiCad 8.0.2} date 2024-08-20T22:37:48-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-08-20T22:37:48-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.000
%
G90
G05
T1
X90.424Y-95.348
X90.424Y-106.778
T2
X129.966Y-90.744
X138.766Y-90.744
T3
X96.774Y-104.648
M30
